# Generated by Django 4.2.3 on 2023-07-27 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_alert', '0002_remove_message_message_title_message_setup_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_level',
            field=models.IntegerField(choices=[(2, 'high'), (1, 'middle'), (0, 'low')], default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
