# Generated by Django 4.2.3 on 2023-07-27 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_alert', '0003_message_message_level_message_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-setup_time']},
        ),
    ]
